### ISSUE TITLE
Can't install Web3Signer - won't start

### ISSUE THREAD

**Issue by InoMurko** [dappnode/DAppNodePackage-web3signer#42]
Reply: Command failed: docker-compose -f /usr/src/app/dnp_repo/web3signer.dnp.dappnode.eth/docker-compose.yml up --detach <&- Container DAppNodePackage-postgres.web3signer.dnp.dappnode.eth Starting Container DAppNodePackage-postgres.web3signer.dnp.dappnode.eth Started Container DAppNodePackage-flyway.web3signer.dnp.dappnode.eth Starting Container DAppNodePackage-flyway.web3signer.dnp.dappnode.eth Started Container DAppNodePackage-flyway.web3signer.dnp.dappnode.eth Waiting Container DAppNodePackage-flyway.web3signer.dnp.dappnode.eth Exited Container DAppNodePackage-web3signer.web3signer.dnp.dappnode.eth Starting Container DAppNodePackage-web3signer.web3signer.dnp.dappnode.eth Started Container DAppNodePackage-web3signer.web3signer.dnp.dappnode.eth Waiting container for service "web3signer" is unhealthy
Error: Command failed: docker-compose -f /usr/src/app/dnp_repo/web3signer.dnp.dappnode.eth/docker-compose.yml up --detach <&-
Container DAppNodePackage-postgres.web3signer.dnp.dappnode.eth  Starting
Container DAppNodePackage-postgres.web3signer.dnp.dappnode.eth  Started
Container DAppNodePackage-flyway.web3signer.dnp.dappnode.eth  Starting
Container DAppNodePackage-flyway.web3signer.dnp.dappnode.eth  Started
Container DAppNodePackage-flyway.web3signer.dnp.dappnode.eth  Waiting
Container DAppNodePackage-flyway.web3signer.dnp.dappnode.eth  Exited
Container DAppNodePackage-web3signer.web3signer.dnp.dappnode.eth  Starting
Container DAppNodePackage-web3signer.web3signer.dnp.dappnode.eth  Started
Container DAppNodePackage-web3signer.web3signer.dnp.dappnode.eth  Waiting
container for service "web3signer" is unhealthy

    at shell (file:///usr/src/app/packages/dappmanager/src/utils/shell.ts:35:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at dockerComposeUpPackage (file:///usr/src/app/packages/dappmanager/src/modules/docker/dockerComposeUp.ts:68:7)
    at runPackages (file:///usr/src/app/packages/dappmanager/src/modules/installer/runPackages.ts:80:5)
    at packageInstall (file:///usr/src/app/packages/dappmanager/src/calls/packageInstall.ts:106:9)
    at file:///usr/src/app/packages/dappmanager/src/api/handler/index.ts:36:22

{
  "name": "web3signer.dnp.dappnode.eth",
  "version": "2.0.0",
  "userSettings": {},
  "options": {}
}

**To Reproduce**

**Screenshots**

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**

**Comment by InoMurko** [comment]
Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.69
dappmanager.dnp.dappnode.eth: 0.2.64, commit: a27021fe
https.dnp.dappnode.eth: 0.1.4
ipfs.dnp.dappnode.eth: 0.2.19
wifi.dnp.dappnode.eth: 0.2.8
wireguard.dnp.dappnode.eth: 0.1.2
System info
dockerComposeVersion: 2.5.0
dockerServerVersion: 20.10.6
dockerCliVersion: 20.10.6
os: debian
versionCodename: bullseye
architecture: amd64
kernel: 5.10.0-9-amd64
Disk usage: 16%
